# Generated by Django 6.0.3 on 2026-03-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
