# Generated by Django 6.0.3 on 2026-04-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('placed', 'Placed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='cart', max_length=20),
        ),
    ]
