[pytest]
django_find_project = false
python_files = tests/*.py
python_classes = Test*
python_functions = test_*
testpaths = /app/tests
addopts = --cov=products --cov-report=term-missing --cov-fail-under=60